spring.cloud.stream.kafka.binder.brokers=localhost:9092

spring.cloud.stream.bindings.greetings-in.destination=test1
spring.cloud.stream.bindings.greetings-in.contentType=text/plain
spring.cloud.stream.bindings.greetings-in.group=foo

spring.cloud.stream.bindings.greetings-out.destination=test-out
spring.cloud.stream.bindings.greetings-out.contentType=text/plain


logging.level.root=INFO